apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yjanssens-website
  namespace: yjanssens
  labels:
    app: yjanssens-website
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: yjanssens.be
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFDTCCA/WgAwIBAgISBqufnsvQTzEZm+ZPMZLW77rgMA0GCSqGSIb3DQEBCwUA
      MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
      EwNSMTIwHhcNMjYwMTMxMjEzMjMyWhcNMjYwNTAxMjEzMjMxWjAXMRUwEwYDVQQD
      Ewx5amFuc3NlbnMuYmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK
      V2NCSqldRqGJbRyBupRtn33uZD6NJhIgBC3K4EWKgUHtK47SkCLZzNeVidcurze/
      cOsVw8pOr3N0XTdJ666DNfdT4RAcI7C0yD8o/+xfdAhsx6L2UR/arAQ0WnXA7fsq
      Pa7S72qt5eHfVJxe+KbL9SZqkn49kZRyep9HAyzb/0bzCDPx4f5cI1iBeWfDyAPo
      W+pf+m9lkIbILGEy4FlQ6qKq2ObQluHr0qxuierZAo54JDhqguOKNG9vbb1GXiNy
      Pg+NFN7AWyToORa/DxhjfA5LKhciFL37YPLeQAsc4iX81qbCGKOfwQxLqmhmxurq
      yek+ui16mUcRV35lAatBAgMBAAGjggI1MIICMTAOBgNVHQ8BAf8EBAMCBaAwHQYD
      VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
      BBYEFGoAFC2xgR1EvJMueIeKLYmt+TXwMB8GA1UdIwQYMBaAFAC1KfItjm8x6JtM
      rXg++tzpDNHSMDMGCCsGAQUFBwEBBCcwJTAjBggrBgEFBQcwAoYXaHR0cDovL3Ix
      Mi5pLmxlbmNyLm9yZy8wKQYDVR0RBCIwIIIQd3d3LnlqYW5zc2Vucy5iZYIMeWph
      bnNzZW5zLmJlMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC4GA1UdHwQnMCUwI6AhoB+G
      HWh0dHA6Ly9yMTIuYy5sZW5jci5vcmcvOTcuY3JsMIIBCwYKKwYBBAHWeQIEAgSB
      /ASB+QD3AHUAyzj3FYl8hKFEX1vB3fvJbvKaWc1HCmkFhbDLFMMUWOcAAAGcFi5b
      fwAABAMARjBEAiAHtMPMEqBCHYyt69oZ/P11O4W2bk9Qx4MVuN3k+4QR9gIgXA2t
      KeOKb8VPDebyUL5OxCHBd+yb/xoAo9e5gGeiI6YAfgAai51pSleYyJmgyoi99I/A
      tFZgzMNgDR9x9Gn/x9GsowAAAZwWLl89AAgAAAUAP7yuhQQDAEcwRQIhAKPSbcUc
      LK1RU0X9dsU6tZjVJiwC4nH7tt2pnJlzjPr0AiAEeN0Jj565vm6HY/G8OT3JFIB1
      RNyPgfawPyMP8DvevjANBgkqhkiG9w0BAQsFAAOCAQEAZB/w1RpoSVdqIjYwyGBD
      gk5PxtEds3POr9yIGxU7uoyjjHxRgf3HeJNMATDBUTfKp74AutQp29jir+GVC32N
      p01AXj49uXjxxz+x9Inlsm6bXkCcIzyxXKoVq03k3N+YoQvH7fOa9NbUDNQxLMIx
      PvCpGcuiKUU43UcLfyaAE3FxzDTaHEbMkmpR/LhAtHJMhHpdpM/f5N3+BAUYsg/e
      cNyc3ds12Y7F+eig8jWHaZRjlxwA78NVboyUY5J5Sh5qKRDqfC3/d6bnm+MsUMo3
      jDpdmEfHkAFo1i2LHk6pcR92Tel3AnejeAF8YC+CkzOF0rnm7jOTAG14sqkb13A5
      BA==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFBjCCAu6gAwIBAgIRAMISMktwqbSRcdxA9+KFJjwwDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
      WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDEMMAoGA1UEAxMDUjEyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
      CgKCAQEA2pgodK2+lP474B7i5Ut1qywSf+2nAzJ+Npfs6DGPpRONC5kuHs0BUT1M
      5ShuCVUxqqUiXXL0LQfCTUA83wEjuXg39RplMjTmhnGdBO+ECFu9AhqZ66YBAJpz
      kG2Pogeg0JfT2kVhgTU9FPnEwF9q3AuWGrCf4yrqvSrWmMebcas7dA8827JgvlpL
      Thjp2ypzXIlhZZ7+7Tymy05v5J75AEaz/xlNKmOzjmbGGIVwx1Blbzt05UiDDwhY
      XS0jnV6j/ujbAKHS9OMZTfLuevYnnuXNnC2i8n+cF63vEzc50bTILEHWhsDp7CH4
      WRt/uTp8n1wBnWIEwii9Cq08yhDsGwIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
      hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
      /wIBADAdBgNVHQ4EFgQUALUp8i2ObzHom0yteD763OkM0dIwHwYDVR0jBBgwFoAU
      ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
      hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
      A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
      AQELBQADggIBAI910AnPanZIZTKS3rVEyIV29BWEjAK/duuz8eL5boSoVpHhkkv3
      4eoAeEiPdZLj5EZ7G2ArIK+gzhTlRQ1q4FKGpPPaFBSpqV/xbUb5UlAXQOnkHn3m
      FVj+qYv87/WeY+Bm4sN3Ox8BhyaU7UAQ3LeZ7N1X01xxQe4wIAAE3JVLUCiHmZL+
      qoCUtgYIFPgcg350QMUIWgxPXNGEncT921ne7nluI02V8pLUmClqXOsCwULw+PVO
      ZCB7qOMxxMBoCUeL2Ll4oMpOSr5pJCpLN3tRA2s6P1KLs9TSrVhOk+7LX28NMUlI
      usQ/nxLJID0RhAeFtPjyOCOscQBA53+NRjSCak7P4A5jX7ppmkcJECL+S0i3kXVU
      y5Me5BbrU8973jZNv/ax6+ZK6TM8jWmimL6of6OrX7ZU6E2WqazzsFrLG3o2kySb
      zlhSgJ81Cl4tv3SbYiYXnJExKQvzf83DYotox3f0fwv7xln1A2ZLplCb0O+l/AK0
      YE0DS2FPxSAHi0iwMfW2nNHJrXcY3LLHD77gRgje4Eveubi2xxa+Nmk/hmhLdIET
      iVDFanoCrMVIpQ59XWHkzdFmoHXHBV7oibVjGSO7ULSQ7MJ1Nz51phuDJSgAIU7A
      0zrLnOrAj/dfrlEWRhCvAgbuwLZX1A2sjNjXoPOHbsPiy+lO1KF8/XY7
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAyldjQkqpXUahiW0cgbqUbZ997mQ+jSYSIAQtyuBFioFB7SuO
      0pAi2czXlYnXLq83v3DrFcPKTq9zdF03SeuugzX3U+EQHCOwtMg/KP/sX3QIbMei
      9lEf2qwENFp1wO37Kj2u0u9qreXh31ScXvimy/UmapJ+PZGUcnqfRwMs2/9G8wgz
      8eH+XCNYgXlnw8gD6FvqX/pvZZCGyCxhMuBZUOqiqtjm0Jbh69Ksbonq2QKOeCQ4
      aoLjijRvb229Rl4jcj4PjRTewFsk6DkWvw8YY3wOSyoXIhS9+2Dy3kALHOIl/Nam
      whijn8EMS6poZsbq6snpProteplHEVd+ZQGrQQIDAQABAoIBAEqO+udRhaj2Ps3Z
      49g1vT3LuGagj6AJOEKN56XLEDTiPj27gCw8qmrhHUtf+Geebwde/3EMrT5jTkLB
      mn7llm+I8jL5Sqtjx1hGNWfRLfNaWURkJ7tl1zwHiKEV+C/4QUWmZwYY7JFZlOpr
      Thd8vlGHavl4M4ZSX4Xzgz9yfxQtC8xVIF1VG4uvle0Bj8nLoESVuBqkimhu0w9/
      7kbTTDKGNn0dZpxUWW0ZXf7P75E2iVfkY39j+28QWiaycqjj9DC/N5ZjIjtxKrSI
      qL0SuihFnWSvgIYEhoWWIwCVgNHHpW4gk2inkYIka/S75mkwTuG0UVdaFnAK6PDU
      jWwTVwECgYEA6+GUmX8iDT1unolhmdvGYkVdQerknydZC6zvjsfWFCzhkjK8c2by
      EptyWShsidHR7JY5SUZ2DPx2I7COJOVjE6bneZy16+FWA8Z6M0zDgj/sqPfjhsLM
      o/L29uGkDeUusOgTgH9xgPnxXR8rWVJ2sy1GcEaAq2zo4VsUv+cg5/ECgYEA25l4
      z8FMDfz+bX0AVhIIzAGN8/wPHPjn59i069+UbkYiTgkUN4VNRUPRAugrtRSm5nG7
      UlMiUTnstvkDQ2jO6IVz/Snk4kkLqHG8X4hEEWqOdLQ2ANIOevdD8+wmxW7SDJdE
      84L6paqthEVANyu7zheQ0YsS3sGtYFGh13ikyFECgYBb6Mm+BYt/HTC9FUqyaLAk
      GmL8DEqIuQw5QGkXeUYxFkvOa3aCgNpR5b/ofZfNG7RwOxiXNJ1K8hQWU/UO61Jv
      ldkbybQY9PRPBEcZNg/38HCGZhCBseWK/GC+Ua1avLI0vDjdGMthNgKWBk8dvsQB
      jOKlXNNF+GnFZXfwTl7EAQKBgAj7wUZ2eN8Fn37pIy9iM3vtAFqf0Bp2UD5aziPs
      FI1iTxr0IiCXUm7n9E/zIX6Z5q38rxYSEpBSF03w5+JFElnOw8zyfsuHA3QTmwop
      b+dqfYNmr+LetPrwzJXY7kkbXHppYce4bvqB/fEwSA05u8gVjLYVw2Lbd3U+Qamn
      5M3RAoGAFbcgxICAp63Y4ifsfeh4gtVVbnjdAKabFqvvIjK7RiZcyYydzRv6q51J
      x/mDIP5RwA3ayEF5zftZHuI4LlX0j95oKy+Mg8/ZJ2LTucfhQSZG1EKm8mup79D6
      /B18a5z2sr7joUYlqUWrYmFF8D1EN4nEBXE+j+8wwDaIpd8MQYg=
      -----END RSA PRIVATE KEY-----
  to:
    kind: Service
    name: yjanssens-website
    weight: 100
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yjanssens-website-www
  namespace: yjanssens
  labels:
    app: yjanssens-website
spec:
  host: www.yjanssens.be
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFDTCCA/WgAwIBAgISBqufnsvQTzEZm+ZPMZLW77rgMA0GCSqGSIb3DQEBCwUA
      MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
      EwNSMTIwHhcNMjYwMTMxMjEzMjMyWhcNMjYwNTAxMjEzMjMxWjAXMRUwEwYDVQQD
      Ewx5amFuc3NlbnMuYmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK
      V2NCSqldRqGJbRyBupRtn33uZD6NJhIgBC3K4EWKgUHtK47SkCLZzNeVidcurze/
      cOsVw8pOr3N0XTdJ666DNfdT4RAcI7C0yD8o/+xfdAhsx6L2UR/arAQ0WnXA7fsq
      Pa7S72qt5eHfVJxe+KbL9SZqkn49kZRyep9HAyzb/0bzCDPx4f5cI1iBeWfDyAPo
      W+pf+m9lkIbILGEy4FlQ6qKq2ObQluHr0qxuierZAo54JDhqguOKNG9vbb1GXiNy
      Pg+NFN7AWyToORa/DxhjfA5LKhciFL37YPLeQAsc4iX81qbCGKOfwQxLqmhmxurq
      yek+ui16mUcRV35lAatBAgMBAAGjggI1MIICMTAOBgNVHQ8BAf8EBAMCBaAwHQYD
      VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
      BBYEFGoAFC2xgR1EvJMueIeKLYmt+TXwMB8GA1UdIwQYMBaAFAC1KfItjm8x6JtM
      rXg++tzpDNHSMDMGCCsGAQUFBwEBBCcwJTAjBggrBgEFBQcwAoYXaHR0cDovL3Ix
      Mi5pLmxlbmNyLm9yZy8wKQYDVR0RBCIwIIIQd3d3LnlqYW5zc2Vucy5iZYIMeWph
      bnNzZW5zLmJlMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC4GA1UdHwQnMCUwI6AhoB+G
      HWh0dHA6Ly9yMTIuYy5sZW5jci5vcmcvOTcuY3JsMIIBCwYKKwYBBAHWeQIEAgSB
      /ASB+QD3AHUAyzj3FYl8hKFEX1vB3fvJbvKaWc1HCmkFhbDLFMMUWOcAAAGcFi5b
      fwAABAMARjBEAiAHtMPMEqBCHYyt69oZ/P11O4W2bk9Qx4MVuN3k+4QR9gIgXA2t
      KeOKb8VPDebyUL5OxCHBd+yb/xoAo9e5gGeiI6YAfgAai51pSleYyJmgyoi99I/A
      tFZgzMNgDR9x9Gn/x9GsowAAAZwWLl89AAgAAAUAP7yuhQQDAEcwRQIhAKPSbcUc
      LK1RU0X9dsU6tZjVJiwC4nH7tt2pnJlzjPr0AiAEeN0Jj565vm6HY/G8OT3JFIB1
      RNyPgfawPyMP8DvevjANBgkqhkiG9w0BAQsFAAOCAQEAZB/w1RpoSVdqIjYwyGBD
      gk5PxtEds3POr9yIGxU7uoyjjHxRgf3HeJNMATDBUTfKp74AutQp29jir+GVC32N
      p01AXj49uXjxxz+x9Inlsm6bXkCcIzyxXKoVq03k3N+YoQvH7fOa9NbUDNQxLMIx
      PvCpGcuiKUU43UcLfyaAE3FxzDTaHEbMkmpR/LhAtHJMhHpdpM/f5N3+BAUYsg/e
      cNyc3ds12Y7F+eig8jWHaZRjlxwA78NVboyUY5J5Sh5qKRDqfC3/d6bnm+MsUMo3
      jDpdmEfHkAFo1i2LHk6pcR92Tel3AnejeAF8YC+CkzOF0rnm7jOTAG14sqkb13A5
      BA==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFBjCCAu6gAwIBAgIRAMISMktwqbSRcdxA9+KFJjwwDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
      WhcNMjcwMzEyMjM1OTU5WjAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDEMMAoGA1UEAxMDUjEyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
      CgKCAQEA2pgodK2+lP474B7i5Ut1qywSf+2nAzJ+Npfs6DGPpRONC5kuHs0BUT1M
      5ShuCVUxqqUiXXL0LQfCTUA83wEjuXg39RplMjTmhnGdBO+ECFu9AhqZ66YBAJpz
      kG2Pogeg0JfT2kVhgTU9FPnEwF9q3AuWGrCf4yrqvSrWmMebcas7dA8827JgvlpL
      Thjp2ypzXIlhZZ7+7Tymy05v5J75AEaz/xlNKmOzjmbGGIVwx1Blbzt05UiDDwhY
      XS0jnV6j/ujbAKHS9OMZTfLuevYnnuXNnC2i8n+cF63vEzc50bTILEHWhsDp7CH4
      WRt/uTp8n1wBnWIEwii9Cq08yhDsGwIDAQABo4H4MIH1MA4GA1UdDwEB/wQEAwIB
      hjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
      /wIBADAdBgNVHQ4EFgQUALUp8i2ObzHom0yteD763OkM0dIwHwYDVR0jBBgwFoAU
      ebRZ5nu25eQBc4AIiMgaWPbpm24wMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAC
      hhZodHRwOi8veDEuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcG
      A1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly94MS5jLmxlbmNyLm9yZy8wDQYJKoZIhvcN
      AQELBQADggIBAI910AnPanZIZTKS3rVEyIV29BWEjAK/duuz8eL5boSoVpHhkkv3
      4eoAeEiPdZLj5EZ7G2ArIK+gzhTlRQ1q4FKGpPPaFBSpqV/xbUb5UlAXQOnkHn3m
      FVj+qYv87/WeY+Bm4sN3Ox8BhyaU7UAQ3LeZ7N1X01xxQe4wIAAE3JVLUCiHmZL+
      qoCUtgYIFPgcg350QMUIWgxPXNGEncT921ne7nluI02V8pLUmClqXOsCwULw+PVO
      ZCB7qOMxxMBoCUeL2Ll4oMpOSr5pJCpLN3tRA2s6P1KLs9TSrVhOk+7LX28NMUlI
      usQ/nxLJID0RhAeFtPjyOCOscQBA53+NRjSCak7P4A5jX7ppmkcJECL+S0i3kXVU
      y5Me5BbrU8973jZNv/ax6+ZK6TM8jWmimL6of6OrX7ZU6E2WqazzsFrLG3o2kySb
      zlhSgJ81Cl4tv3SbYiYXnJExKQvzf83DYotox3f0fwv7xln1A2ZLplCb0O+l/AK0
      YE0DS2FPxSAHi0iwMfW2nNHJrXcY3LLHD77gRgje4Eveubi2xxa+Nmk/hmhLdIET
      iVDFanoCrMVIpQ59XWHkzdFmoHXHBV7oibVjGSO7ULSQ7MJ1Nz51phuDJSgAIU7A
      0zrLnOrAj/dfrlEWRhCvAgbuwLZX1A2sjNjXoPOHbsPiy+lO1KF8/XY7
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAyldjQkqpXUahiW0cgbqUbZ997mQ+jSYSIAQtyuBFioFB7SuO
      0pAi2czXlYnXLq83v3DrFcPKTq9zdF03SeuugzX3U+EQHCOwtMg/KP/sX3QIbMei
      9lEf2qwENFp1wO37Kj2u0u9qreXh31ScXvimy/UmapJ+PZGUcnqfRwMs2/9G8wgz
      8eH+XCNYgXlnw8gD6FvqX/pvZZCGyCxhMuBZUOqiqtjm0Jbh69Ksbonq2QKOeCQ4
      aoLjijRvb229Rl4jcj4PjRTewFsk6DkWvw8YY3wOSyoXIhS9+2Dy3kALHOIl/Nam
      whijn8EMS6poZsbq6snpProteplHEVd+ZQGrQQIDAQABAoIBAEqO+udRhaj2Ps3Z
      49g1vT3LuGagj6AJOEKN56XLEDTiPj27gCw8qmrhHUtf+Geebwde/3EMrT5jTkLB
      mn7llm+I8jL5Sqtjx1hGNWfRLfNaWURkJ7tl1zwHiKEV+C/4QUWmZwYY7JFZlOpr
      Thd8vlGHavl4M4ZSX4Xzgz9yfxQtC8xVIF1VG4uvle0Bj8nLoESVuBqkimhu0w9/
      7kbTTDKGNn0dZpxUWW0ZXf7P75E2iVfkY39j+28QWiaycqjj9DC/N5ZjIjtxKrSI
      qL0SuihFnWSvgIYEhoWWIwCVgNHHpW4gk2inkYIka/S75mkwTuG0UVdaFnAK6PDU
      jWwTVwECgYEA6+GUmX8iDT1unolhmdvGYkVdQerknydZC6zvjsfWFCzhkjK8c2by
      EptyWShsidHR7JY5SUZ2DPx2I7COJOVjE6bneZy16+FWA8Z6M0zDgj/sqPfjhsLM
      o/L29uGkDeUusOgTgH9xgPnxXR8rWVJ2sy1GcEaAq2zo4VsUv+cg5/ECgYEA25l4
      z8FMDfz+bX0AVhIIzAGN8/wPHPjn59i069+UbkYiTgkUN4VNRUPRAugrtRSm5nG7
      UlMiUTnstvkDQ2jO6IVz/Snk4kkLqHG8X4hEEWqOdLQ2ANIOevdD8+wmxW7SDJdE
      84L6paqthEVANyu7zheQ0YsS3sGtYFGh13ikyFECgYBb6Mm+BYt/HTC9FUqyaLAk
      GmL8DEqIuQw5QGkXeUYxFkvOa3aCgNpR5b/ofZfNG7RwOxiXNJ1K8hQWU/UO61Jv
      ldkbybQY9PRPBEcZNg/38HCGZhCBseWK/GC+Ua1avLI0vDjdGMthNgKWBk8dvsQB
      jOKlXNNF+GnFZXfwTl7EAQKBgAj7wUZ2eN8Fn37pIy9iM3vtAFqf0Bp2UD5aziPs
      FI1iTxr0IiCXUm7n9E/zIX6Z5q38rxYSEpBSF03w5+JFElnOw8zyfsuHA3QTmwop
      b+dqfYNmr+LetPrwzJXY7kkbXHppYce4bvqB/fEwSA05u8gVjLYVw2Lbd3U+Qamn
      5M3RAoGAFbcgxICAp63Y4ifsfeh4gtVVbnjdAKabFqvvIjK7RiZcyYydzRv6q51J
      x/mDIP5RwA3ayEF5zftZHuI4LlX0j95oKy+Mg8/ZJ2LTucfhQSZG1EKm8mup79D6
      /B18a5z2sr7joUYlqUWrYmFF8D1EN4nEBXE+j+8wwDaIpd8MQYg=
      -----END RSA PRIVATE KEY-----
  to:
    kind: Service
    name: yjanssens-website
    weight: 100
