apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: router-tls-secret-reader
  namespace: yjanssens
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["yjanssens-tls"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: router-tls-secret-reader
  namespace: yjanssens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: router-tls-secret-reader
subjects:
  - kind: ServiceAccount
    name: router
    namespace: openshift-ingress
