apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yjanssens-website
  namespace: yjanssens
  labels:
    app: yjanssens-website
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: yjanssens.be
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    externalCertificate:
      name: yjanssens-tls
  to:
    kind: Service
    name: yjanssens-website
    weight: 100
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yjanssens-website-www
  namespace: yjanssens
  labels:
    app: yjanssens-website
spec:
  host: www.yjanssens.be
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    externalCertificate:
      name: yjanssens-tls
  to:
    kind: Service
    name: yjanssens-website
    weight: 100
