apiVersion: v1
kind: Service
metadata:
  name: yjanssens-website
  namespace: yjanssens
  labels:
    app: yjanssens-website
    app.kubernetes.io/name: yjanssens-website
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: yjanssens-website
